include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false



analyzer:
#   exclude:
#     - path/to/excluded/files/**
